PS C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d> python .\test1.py
[COL2IM] Output shape: (1, 1, 130, 130), min: -36.842115, max: 38.534427, mean: -0.047547, std: 8.733185
[CHECK COL2IM] Extra region (128:, 128:): min=-0.258755, max=6.621229, mean=2.044740
Traceback (most recent call last):
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 190, in <module>
    test_col2im()
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 186, in test_col2im
    assert np.all(extra_region == 0), "❌ col2im có lỗi, phần biên không bằng 0!"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ❌ col2im có lỗi, phần biên không bằng 0!
PS C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d> python .\test1.py
[COL2IM] Output shape: (1, 1, 130, 130), min: -35.825694, max: 32.573368, mean: 0.010349, std: 8.708491
[CHECK COL2IM] Extra region (128:, 128:): min=-3.191685, max=2.119302, mean=-0.051707
Traceback (most recent call last):
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 190, in <module>
    test_col2im()
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 186, in test_col2im
    assert np.all(extra_region == 0), "❌ col2im có lỗi, phần biên không bằng 0!"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ❌ col2im có lỗi, phần biên không bằng 0!
PS C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d> python .\test1.py
Traceback (most recent call last):
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 192, in <module>
    test_col2im()
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 184, in test_col2im
    output = col2im(cols, input_shape, kernel_size, stride)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 158, in col2im
    cols_reshaped = cols.reshape(batch_size, H_out, W_out, in_channels, k, k)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 147456 into shape (1,127,127,1,3,3)
PS C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d> python .\test1.py
[COL2IM] Output shape: (1, 1, 130, 130), min: -35.045179, max: 38.257549, mean: 0.028849, std: 8.824157
Traceback (most recent call last):
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 194, in <module>
    test_col2im()
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 190, in test_col2im
    assert np.all(extra_region == 0), "❌ col2im có lỗi, phần biên không bằng 0!"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ❌ col2im có lỗi, phần biên không bằng 0!
PS C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d> python .\test1.py
[COL2IM] Output shape: (1, 1, 130, 130), min: -3.792032, max: 3.890971, mean: 0.011899, std: 0.994946
[CHECK COL2IM] Extra region (128:, 128:): min=-0.914149, max=1.246152, mean=0.339915
Traceback (most recent call last):
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 202, in <module>
    test_col2im()
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 198, in test_col2im
    assert np.all(extra_region == 0), "❌ col2im có lỗi, phần biên không bằng 0!"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ❌ col2im có lỗi, phần biên không bằng 0!
PS C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d> python .\test1.py
[COL2IM] Output shape: (1, 1, 130, 130), min: -3.916589, max: 4.168834, mean: 0.022536, std: 0.998697
[CHECK COL2IM] Extra region (128:, 128:): min=-1.602973, max=0.133431, mean=-0.621266
Traceback (most recent call last):
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 211, in <module>
    test_col2im()
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 207, in test_col2im
    assert np.all(extra_region == 0), "❌ col2im có lỗi, phần biên không bằng 0!"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ❌ col2im có lỗi, phần biên không bằng 0!
PS C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d> python .\test1.py
[COL2IM] Output shape: (1, 1, 130, 130), min: -4.075867, max: 4.056292, mean: 0.005944, std: 1.004084
[CHECK COL2IM] Extra region (128:, 128:): min=-1.302132, max=1.546444, mean=0.330079
Traceback (most recent call last):
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 211, in <module>
    test_col2im()
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 207, in test_col2im
    assert np.all(extra_region == 0), "❌ col2im có lỗi, phần biên không bằng 0!"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ❌ col2im có lỗi, phần biên không bằng 0!
PS C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d> python .\test1.py
[COL2IM] Output shape: (1, 1, 130, 130), min: -3.598511, max: 3.894644, mean: -0.003657, std: 0.998085
[CHECK COL2IM] Extra region (128:, 128:): min=-0.057791, max=1.749407, mean=0.649937
Traceback (most recent call last):
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 214, in <module>
    test_col2im()
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 210, in test_col2im
    assert np.all(extra_region == 0), "❌ col2im có lỗi, phần biên không bằng 0!"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ❌ col2im có lỗi, phần biên không bằng 0!
PS C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d> python .\test1.py
[TEST] Max Error: 0.000000
[CHECK COL2IM] Extra region (128:, 128:): min=-0.618032, max=1.480992, mean=0.531479
Traceback (most recent call last):
  File "C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d\test1.py", line 205, in <module>
    assert np.all(extra_region == 0), "❌ col2im có lỗi, phần biên không bằng 0!"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ❌ col2im có lỗi, phần biên không bằng 0!
PS C:\Personal\final_graduate\study_CNN\Study_CNN\conv2d> 